### ISSUE TITLE
Deezer backup: run another command, e.g. yt-dlp

### ISSUE THREAD

**Issue by wokkieman** [jbh-cloud/spotify_sync#16]
In case Deezer doesn't have the song, is it possible to run another command  to use YouTube as a source?

Or as alternative, output a list which can be used as input for another script?

**Comment by jbh-cloud** [comment]
@rjwonder adding a command to export unmatched songs in a yt-dlp format is super simple. However I'm not particularly familiar with it so any guidance on what the command you would normally run to dl via yt-dlp would be helpful.

I'm also considering a further refactor to allow multiple backends (e.g. [Tidal-Media-Downloader](https://github.com/yaronzz/Tidal-Media-Downloader) and/or yt-dlp so that spotify_sync and handle it all without you having to perform extra logic elsewhere, assuming I have enough time.

In the interim, assuming you are using a machine with access to [jq](https://stedolan.github.io/jq/) you can pretty much do this yourself. 

For instance to get a list of all songs that failed to match in the format of "%SpotifyArtist% - %SpotifyTitle%"...

- Find your persistent data folder ```python3.9 -m spotify_sync config list-paths``` and cd into..

- Ensure you have a file matching ```processed-*.json```

- The run the following: 
- ```cat processed-%INSERT_YOURS%.json | jq '.[] | select(.matched == false) | .spotify_artist + " - " + .spotify_title'```

**Comment by jbh-cloud** [comment]
@rjwonder showing songs that failed to match is now supported in 1.1.0
